### ISSUE TITLE
spectacular response shape introspection fails for this serializer field

### ISSUE THREAD

**Issue by ksdme** [viper-development/drf-imgproxy#9]
Here's the field descriptor generated by spectacular for a serializer with this field:

```
        profile_picture_thumbnails:
          type: string
          format: uri
          readOnly: true
```

It would be much better if the shape was right and included the per resolution break down.
